# Generated by Django 4.1.5 on 2023-04-17 17:54

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades2',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('NIT', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('fechaFundacion', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('paginaWeb', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpresaApp.empresas')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpresaApp.ciudades2')),
            ],
            options={
                'db_table': 'Sedes',
            },
        ),
    ]
