# Generated by Django 4.1.7 on 2023-04-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('NIT', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=100)),
                ('fechaFundacion', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('paginaWeb', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpresaApp.ciudades')),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
    ]
