# Generated by Django 4.1.7 on 2023-04-11 05:47

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades2',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Ciudades',
            },
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='id',
        ),
        migrations.AddField(
            model_name='empresas',
            name='NIT',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='empresas',
            table='Empresas',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmpresaApp.ciudades2'),
        ),
    ]
