# Generated by Django 4.1.5 on 2023-04-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpresaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='mision',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='vision',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
